# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2_0yl4mUxGTJs2ymfaI108so63MViHN
"""

def awesomeFunction():
  print(1+1)
  print('Hello World')

awesomeFunction()

def SuperAwesomeFuntion(input1,input2):
  prod=input1*input2
  summ=input1+input2

  return prod,summ

out1,out2 = SuperAwesomeFuntion(1,2)
print(out1)
print(out2)

# lambda function
funname = lambda x : x**2 -3

funname(3)

#create a function that computes a factorial
#4! = 4*3*2*1

import numpy as np

n=4

np.prod(np.arange(1,n+1))

import numpy as np

def myfactorial(n):
  return np.prod(np.arange(1,n+1))

myfactorial(13)

import math

math.factorial(13)